version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2022
configuration: Release
platform: x64
clone_folder: c:\projects\ntcall64
build:
  project: Source/NtCall64.sln
  verbosity: normal